chore(maven): explain how to setup maven settings
bonitasoft/bonita-continuous-delivery-doc pull request #132
Opened 2019-07-19 10:18 UTC by laurentleseigneur

explain how to to add `settings.xml` file

2019-09-17 13:01 UTC, tnguyen1 commented
retest this please

2020-12-18 08:42 UTC, uguy requested changes
I would suggest to use volume binding to `/home/bonita/.m2/settings.xml` instead of a docker copy. 

Maybe this is a place to explain that a user can also bind the host `.m2/repository/` folder starting from BCD 3.4.x to benefit from already cached artifacts

2020-12-21 08:22 UTC, laurentleseigneur commented on md/troubleshooting_guide.md
> +docker cp <PATH-TO-SETTINGS.xml> bcd-controller:/home/bonita/.m2/settings.xml
we may keep this, since if we have an already container, the docker cp avoids to restart the container,

and add a mention about mounting a volume for /home/bonita/.m2 that could include also bind settings & repository

2020-12-28 09:46 UTC, uguy commented
Refer to [BCD-464](https://bonitasoft.atlassian.net/browse/BCD-464)

2020-12-29 14:39 UTC, laurentleseigneur reviewed
LGTM

2020-12-29 14:39 UTC, laurentleseigneur commented on md/livingapp_build.md
> +:fa-lightbulb-o: Starting from BCD 3.4, you can directly mount your local `~/.m2` folder to the `/home/bonita/.m2` folder in BCD controller using docker volume !
we may explicit to `3.4.0`
it's not `local`, but `docker host` folder

2020-12-29 14:39 UTC, laurentleseigneur commented on md/livingapp_build.md
> +You will benefit from your already defined maven configuration, and the already cached maven artifacts in your `~/.m2/repository` folder
... and also use docker host `settings.xml` so that your corporate maven artifact manager can handle internet proxy

2020-12-29 14:40 UTC, laurentleseigneur commented
just added minor change in comment

2020-12-29 14:43 UTC, uguy commented on md/livingapp_build.md
> +:fa-lightbulb-o: Starting from BCD 3.4, you can directly mount your local `~/.m2` folder to the `/home/bonita/.m2` folder in BCD controller using docker volume !
ok

2020-12-29 14:46 UTC, uguy commented on md/livingapp_build.md
> +You will benefit from your already defined maven configuration, and the already cached maven artifacts in your `~/.m2/repository` folder
ok

2020-12-29 14:54 UTC, merged