feat(BCD-419): doc for new deployment mode in bcd cli
bonitasoft/bonita-continuous-delivery-doc pull request #147
Opened 2020-03-02 10:40 UTC by uguy

WIP: pull request used for CI

2020-03-02 10:41 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bonitasoft/bonita-continuous-delivery-doc?pullRequest=147) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bonitasoft/bonita-continuous-delivery-doc?pullRequest=147) before we can accept your contribution.<br/><hr/>**hugues.bretin** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bonitasoft/bonita-continuous-delivery-doc?pullRequest=147) it.</sub>

2020-03-02 14:24 UTC, florentsarat commented on md/release_notes.md
> +* Starting with release 3.3.0, BCD offer two deployment mode `development` and `production` and allow for improved policy management.
* Starting with the release 3.3.0, BCD introduces deployments modes (`development` and `production`) to manage easily artifacts policies.
::: warning
The default deployment policies are changing from the previous BCD versions. More information [here](upgrade_bcd.md)
:::

2020-03-02 14:28 UTC, florentsarat commented on md/livingapp_deploy.md
> +You can also add a **--development-mode** flag to enable a deployment in development mode. This flag allow for more agressive replacement policy. When this flag is not provided, the default productio
You can also add a **--development-mode** flag to perform the deployment in development mode. This flag allows for a more aggressive replacement policy. When this flag is not provided, the default production mode will be used which means more artifacts will be preserved.

2020-03-02 14:29 UTC, uguy commented on md/release_notes.md
> +* Starting with release 3.3.0, BCD offer two deployment mode `development` and `production` and allow for improved policy management.
Ok for me. Any way to add your changes automatically ?

2020-03-02 14:29 UTC, uguy commented on md/livingapp_deploy.md
> +You can also add a **--development-mode** flag to enable a deployment in development mode. This flag allow for more agressive replacement policy. When this flag is not provided, the default productio
same as above :+1:

2020-03-02 15:09 UTC, tnguyen1 requested changes
This PR needs to be rebased on a 3.3 branch btw.

2020-03-02 15:09 UTC, tnguyen1 commented on md/bcd_cli.md
> +<dl class="option">
This is not meant to be described on this page.
This page should reflect what the CLI help looks like. It is automatically generated from the CLI help output.

2020-03-02 15:09 UTC, tnguyen1 commented on md/livingapp_build_and_deploy.md
> +Don't forget to add the `--development-mode` to the arguments if want to apply development policies (ex: replace organization, etc.)
```suggestion
Make sure to add the `--development-mode` option if you want to deploy using Development policies (eg. replace processes and profiles, merge organization data). Otherwise Production deployment policies will be used (eg. existing processes are left untouched).
```

2020-03-02 15:09 UTC, tnguyen1 commented on md/release_notes.md
> +* Starting with the release 3.3.0, BCD introduces deployments modes (`development` and `production`) to manage easily artifacts policies.
```suggestion
* With release 3.3.0, BCD introduces deployment modes (_Development_ and _Production_) to manage artifacts deployment policies more easily.
```

2020-03-02 15:09 UTC, tnguyen1 commented on md/release_notes.md
> +* Starting with the release 3.3.0, BCD introduces deployments modes (`development` and `production`) to manage easily artifacts policies.
I think this would also need further details regarding this breaking change (we could mention it as a *breaking change* too btw).

2020-03-02 15:09 UTC, tnguyen1 commented on md/upgrade_bcd.md
> +Starting from version `3.3`, bcd cli default deployment mode is production. While this is safer for production target, when using bcd for development, ensure that you add `--development-mode` to the
```suggestion
Starting from version `3.3.0`, bcd livingapp default deployment mode is production. While this is safer for production target, when using bcd for development, ensure that you add `--development-mode` to the arguments.
```

2020-03-02 15:55 UTC, florentsarat commented on md/release_notes.md
> +* Starting with the release 3.3.0, BCD introduces deployments modes (`development` and `production`) to manage easily artifacts policies.
What do you think of this new version?

2020-03-02 16:24 UTC, tnguyen1 requested changes

2020-03-02 16:24 UTC, tnguyen1 commented on md/release_notes.md
> +More information on how to upgrade you BCD [here](upgrade_bcd.md)
We should remove this sentence as I think we should remove the "upgrade" part. It's a new option, this does not involve file changes.
```suggestion

```

2020-03-02 16:24 UTC, tnguyen1 commented on md/upgrade_bcd.md
> +```
I don't think this new option requires any file changes or upgrade. Hence I suggest to remove this section.
```suggestion

```

2020-03-02 16:24 UTC, tnguyen1 commented on md/release_notes.md
> +### Breaking changes
Move the "breaking changes" part as presented on this page: https://documentation.bonitasoft.com/bcd/2.0/release_notes

The "breaking changes" part could only contain the fact that the "--development-mode" must be used to maintain the behaviour from previous versions.

Then the "What's new" could go deeper with the deployment mode table. :+1:

2020-03-09 10:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/bonitasoft/bonita-continuous-delivery-doc?pullRequest=147) <br/>All committers have signed the CLA.

2020-03-09 11:55 UTC, tnguyen1 approved these changes

2020-03-09 11:56 UTC, merged