feat(custom-init): add tutorial for custom-init.d abilities (BCD-97)
bonitasoft/bonita-continuous-delivery-doc pull request #16
Opened 2017-12-08 15:05 UTC by tnguyen1

2017-12-13 16:43 UTC, tbouffard requested changes
Pretty clear, good job

I would put a warning about the logo modification (see my comments in commits)

2017-12-13 16:43 UTC, tbouffard commented on md/custom_init.md
> +### replace-logo.sh
I would not put this example or put a warning as this is not supported
The right way to do this is to create a custom theme (sp only feature) and to upload it into the portal. For sure, this will be easier when artifacts deployment tools will be available in BCD.

See https://documentation.bonitasoft.com/bonita/7.6/creating-a-new-look-feel

2017-12-13 16:43 UTC, tbouffard commented on md/custom_init.md
> +### add-javamelody.sh
IHMO, when possible, the end user should not modify the bonita war as this may produce side effects.

I have seen in the documentation that this is the way to do it for event-handler (https://documentation.bonitasoft.com/bonita/7.6/event-handlers) or password policy (https://documentation.bonitasoft.com/bonita/7.6/enforce-password-policy).

This is ok for now as we do not provide extension points (in 7.6 we have an experimental plugins mode), but keep in mind that this should change in the future 😸

2017-12-14 08:37 UTC, tnguyen1 commented on md/custom_init.md
> +### add-javamelody.sh
Agreed we should avoid altering `bonita.war`... Haven't found another example to demonstrate this feature without modifying `bonita.war` though. Any ideas are welcome!
Also looking forward to this "plugins mode"! :-)

2017-12-14 08:40 UTC, tnguyen1 commented on md/custom_init.md
> +### replace-logo.sh
I have no problem removing this example if it may raise confusion with customers. Would be happy to read other opinions though - cc @JeremJR @abirembaut @philippebonita what do you think?

2017-12-14 08:54 UTC, JeremJR commented on md/custom_init.md
> +### replace-logo.sh
I am agreed that it could lead to confusion. It could be better to wait till we can use the look & feel feature.

2017-12-14 09:03 UTC, JeremJR requested changes

2017-12-14 09:03 UTC, JeremJR commented on md/custom_init.md
> +### activate-all-dynamic-checks.sh
We could avoid that as there is already a docker variable called REST_API_DYN_AUTH_CHECKS which is set to true by default.

2017-12-14 09:39 UTC, tnguyen1 commented on md/custom_init.md
> +### replace-logo.sh
OK will remove this example.

2017-12-14 09:41 UTC, tnguyen1 commented on md/custom_init.md
> +### activate-all-dynamic-checks.sh
Forgot this feature from Docker image... :sweat_smile: - Will remove this example then.

2017-12-14 10:41 UTC, tnguyen1 commented
Updated with your feedbacks in fa2d125 @tbouffard @JeremJR

2017-12-14 12:33 UTC, tbouffard approved these changes

2017-12-14 12:33 UTC, tbouffard commented
I have just checked the new commit, LGTM

2017-12-14 15:41 UTC, JeremJR commented on md/custom_init.md
> +### add-javamelody.sh
each access to /bonita/monitoring raised this error : 
```
14-Dec-2017 14:49:31.697 WARNING [http-nio-8080-exec-5] net.bull.javamelody.internal.common.JavaLogger.warn org.quartz.JobPersistenceException: Couldn't obtain job groups: error enlisting a JdbcConnectionHandle of a JdbcPooledConnection from datasource jdbc/bonitaDSXA in state ACCESSIBLE with usage count 1 wrapping org.postgresql.xa.PGXAConnection@21205828 on Pooled connection wrapping physical connection org.postgresql.jdbc4.Jdbc4Connection@6d54cf57 [See nested exception: java.sql.SQLException: error enlisting a JdbcConnectionHandle of a JdbcPooledConnection from datasource jdbc/bonitaDSXA in state ACCESSIBLE with usage count 1 wrapping org.postgresql.xa.PGXAConnection@21205828 on Pooled connection wrapping physical connection org.postgresql.jdbc4.Jdbc4Connection@6d54cf57]
 org.quartz.JobPersistenceException: Couldn't obtain job groups: error enlisting a JdbcConnectionHandle of a JdbcPooledConnection from datasource jdbc/bonitaDSXA in state ACCESSIBLE with usage count 1 wrapping org.postgresql.xa.PGXAConnection@21205828 on Pooled connection wrapping physical connection org.postgresql.jdbc4.Jdbc4Connection@6d54cf57 [See nested exception: java.sql.SQLException: error enlisting a JdbcConnectionHandle of a JdbcPooledConnection from datasource jdbc/bonitaDSXA in state ACCESSIBLE with usage count 1 wrapping org.postgresql.xa.PGXAConnection@21205828 on Pooled connection wrapping physical connection org.postgresql.jdbc4.Jdbc4Connection@6d54cf57]
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.getJobGroupNames(JobStoreSupport.java:2041)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport$25.execute(JobStoreSupport.java:2028)
	at org.quartz.impl.jdbcjobstore.JobStoreCMT.executeInLock(JobStoreCMT.java:245)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeWithoutLock(JobStoreSupport.java:3723)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.getJobGroupNames(JobStoreSupport.java:2025)
	at org.quartz.core.QuartzScheduler.getJobGroupNames(QuartzScheduler.java:1447)
	at org.quartz.impl.StdScheduler.getJobGroupNames(StdScheduler.java:451)
	at net.bull.javamelody.internal.model.Quartz2Adapter.getAllJobsOfScheduler(Quartz2Adapter.java:149)
	at net.bull.javamelody.internal.model.JobInformations.buildJobInformationsList(JobInformations.java:163)
	at net.bull.javamelody.internal.model.JavaInformations.<init>(JavaInformations.java:188)
	at net.bull.javamelody.internal.web.MonitoringController.doActionIfNeededAndReport(MonitoringController.java:155)
	at net.bull.javamelody.MonitoringFilter.doMonitoring(MonitoringFilter.java:396)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:200)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:394)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: error enlisting a JdbcConnectionHandle of a JdbcPooledConnection from datasource jdbc/bonitaDSXA in state ACCESSIBLE with usage count 1 wrapping org.postgresql.xa.PGXAConnection@21205828 on Pooled connection wrapping physical connection org.postgresql.jdbc4.Jdbc4Connection@6d54cf57
	at bitronix.tm.resource.jdbc.JdbcConnectionHandle.enlistResource(JdbcConnectionHandle.java:87)
	at bitronix.tm.resource.jdbc.JdbcConnectionHandle.prepareStatement(JdbcConnectionHandle.java:242)
	at sun.reflect.GeneratedMethodAccessor74.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at bitronix.tm.resource.jdbc.BaseProxyHandlerClass.invoke(BaseProxyHandlerClass.java:64)
	at com.sun.proxy.$Proxy14.prepareStatement(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.invoke(AttributeRestoringConnectionInvocationHandler.java:73)
	at com.sun.proxy.$Proxy14.prepareStatement(Unknown Source)
	at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.selectJobGroups(StdJDBCDelegate.java:940)
	at org.quartz.impl.jdbcjobstore.JobStoreSupport.getJobGroupNames(JobStoreSupport.java:2039)
	... 36 more
Caused by: bitronix.tm.internal.BitronixSystemException: resource 'jdbc/bonitaDSXA' cannot be used outside XA transaction scope. Set allowLocalTransactions to true if you want to allow this and you know your resource supports this.
	at bitronix.tm.resource.common.TransactionContextHelper.enlistInCurrentTransaction(TransactionContextHelper.java:78)
	at bitronix.tm.resource.jdbc.JdbcConnectionHandle.enlistResource(JdbcConnectionHandle.java:85)
	... 49 more

```
maybe that we could protect this url by bonita authentication? here is a slightly modification : 
```
#!/bin/bash

set -euxo pipefail

indicator_path=/opt/$(basename $BASH_ARGV)-executed
if [ -f ${indicator_path} ]; then
  echo "Custom script already executed" && return 0
fi

BONITA_PATH=${BONITA_PATH:-/opt/bonita}
BONITA_FILES=${BONITA_FILES:-/opt/files}


war_path=$(find "${BONITA_PATH}/Bonita"*"Subscription-${BONITA_VERSION}-Tomcat-${TOMCAT_VERSION}/server/webapps" -name bonita.war)
workdir="${BONITA_FILES}/add-javamelody"

rm -rf ${workdir} && mkdir -p ${workdir}

pushd ${workdir}

# download javamelody jars
mkdir -p WEB-INF/lib
pushd WEB-INF/lib
curl -sSLOJ https://github.com/javamelody/javamelody/releases/download/javamelody-core-1.70.0/javamelody-core-1.70.0.jar
curl -sSLOJ https://repo1.maven.org/maven2/org/jrobin/jrobin/1.5.9/jrobin-1.5.9.jar
popd

# add url into the authentication filter
unzip -q -c "${war_path}" WEB-INF/web.xml > WEB-INF/web.xml
sed -i '/<filter-name>AuthenticationFilter<\/filter-name>/a \\t<url-pattern>\/monitoring<\/url-pattern>' WEB-INF/web.xml

# repackage war
zip -r "${war_path}" WEB-INF

# Create indicator file
touch ${indicator_path}
```

2017-12-15 16:41 UTC, tnguyen1 commented on md/custom_init.md
> +### add-javamelody.sh
1. I did not manage to configure JavaMelody to avoid this annoying WARNING message. :-(
So I am afraid we will have to remove this example.

2. Meanwhile I found another option to add authorization to /monitoring resource using JavaMelody System property. Here's the script (which shows how to customize `CATALINA_OPTS` which might be interesting):
```bash
#!/bin/bash

set -euxo pipefail

indicator_path=/opt/$(basename $BASH_ARGV)-executed
if [ -f ${indicator_path} ]; then
  echo "Custom script already executed" && return 0
fi

BONITA_PATH=${BONITA_PATH:-/opt/bonita}
BONITA_FILES=${BONITA_FILES:-/opt/files}
BONITA_SETUP_SH="${BONITA_PATH}/Bonita*Subscription-${BONITA_VERSION}-Tomcat-${TOMCAT_VERSION}/setup/setup.sh"


war_path=$(find "${BONITA_PATH}/Bonita"*"Subscription-${BONITA_VERSION}-Tomcat-${TOMCAT_VERSION}/server/webapps" -name bonita.war)
workdir="${BONITA_FILES}/add-javamelody"

rm -rf ${workdir} && mkdir -p ${workdir}

pushd ${workdir}

# download javamelody jars
mkdir -p WEB-INF/lib
pushd WEB-INF/lib
curl -sSLOJ https://github.com/javamelody/javamelody/releases/download/javamelody-core-1.70.0/javamelody-core-1.70.0.jar
curl -sSLOJ https://repo1.maven.org/maven2/org/jrobin/jrobin/1.5.9/jrobin-1.5.9.jar
popd

# add url into the authentication filter
#unzip -q -c "${war_path}" WEB-INF/web.xml > WEB-INF/web.xml
#sed -i '/<filter-name>AuthenticationFilter<\/filter-name>/a \\t<url-pattern>\/monitoring<\/url-pattern>' WEB-INF/web.xml

# repackage war
zip -r "${war_path}" WEB-INF

# configure JavaMelody through System properties
pushd ${BONITA_PATH}/Bonita*Subscription-${BONITA_VERSION}-Tomcat-${TOMCAT_VERSION}
sed -i setup/tomcat-templates/setenv.sh -e \
  '/export CATALINA_OPTS/i CATALINA_OPTS="${CATALINA_OPTS} -Djavamelody.authorized-users=monitoring:password"'
${BONITA_SETUP_SH} configure

# Create indicator file
touch ${indicator_path}
```

2017-12-20 16:06 UTC, JeremJR commented on md/custom_init.md
> +### add-javamelody.sh
I've tested the event handler example and it's ok for me.
Indeed, regarding java melody, if we can't remove the warning message, it will be better to remove this example.

2017-12-21 11:22 UTC, tnguyen1 commented
Removed JavaMelody example with commit 0f0a8ec.

2017-12-21 13:06 UTC, JeremJR approved these changes

2017-12-21 13:06 UTC, merged