doc(deploy): describe policy override and defaults
bonitasoft/bonita-continuous-delivery-doc pull request #191
Opened 2022-05-10 13:04 UTC by uguy

2022-05-10 14:29 UTC, JeremJR requested changes

2022-05-10 14:29 UTC, JeremJR commented on modules/ROOT/pages/livingapp_deploy.adoc
> +- If no policy is specified in the `deploy.json` file, the policy specified as a CLI options will be applied.
```suggestion
- If a deploy policy is declared in a `deploy.json` file, it overrides the policy specified as a CLI option (like `--development-mode`).
- If no policy is specified in the `deploy.json` file, the policy specified as a CLI option will be applied.
```

2022-05-10 14:29 UTC, JeremJR commented on modules/ROOT/pages/livingapp_deploy.adoc
> +- If a deploy policy is declared in a `deploy.json` file, it overrides the policy specified as a CLI options (like `--development-mode`).
You say "like `--development-mode`" but is there other ways to specify policies with a CLI option?

2022-05-10 14:36 UTC, JeremJR commented on modules/ROOT/pages/livingapp_deploy.adoc
> +- Application: `REPLACE_DUPLICATES`
There is not policy for Pages, Layouts, Themes, BusinessDataModel and BdmAccessControl too?

2022-05-12 15:26 UTC, uguy commented on modules/ROOT/pages/livingapp_deploy.adoc
> +- Application: `REPLACE_DUPLICATES`
Nothing like this found in the code for them.

2022-05-12 15:28 UTC, merged