feat: add AWS Organizations support BCD-194 and GSuite SSO support BC…
bonitasoft/bonita-continuous-delivery-doc pull request #24
Opened 2018-01-30 09:09 UTC by JeremJR

…D-195

2018-02-01 15:05 UTC, tnguyen1 commented
retest this please

2018-02-01 15:12 UTC, tnguyen1 commented
retest this please

2018-02-01 15:28 UTC, tnguyen1 commented
retest this please

2018-02-01 15:46 UTC, tnguyen1 commented
retest this please

2018-02-02 14:24 UTC, tnguyen1 requested changes

2018-02-02 14:24 UTC, tnguyen1 commented on md/aws_prerequisites.md
> +1. Create an IAM Policy to allow ec2 instances of a cluster to autodiscover themselves on a specific region (eg. us-west-2).
This is related to a (justified) breaking change.
This means BCD no longer supports deploying a cluster on AWS using access key and secret key. We are enforcing IAM role here as recommended here: https://github.com/hazelcast/hazelcast-aws#iam-roles
We should be more explicit on this change I think. (only required for cluster on AWS + using access and secret keys are no longer supported)

2018-02-02 14:24 UTC, tnguyen1 commented on md/aws_prerequisites.md
> +1. Create an IAM Policy to grant access on [Instance Profile](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2_instance-profiles.html) management
I think we can avoid this step as when we create the `ClusterBCD` role through the AWS Console (as documented after), AWS automatically creates an Instance Profile.
Then we could re-use this Instance Profile instead of creating it with Terraform.
So this section could be removed.

Also, if we could retrieve the Instance Profile ID automatically from the role name (instead of asking the customer to copy it from AWS Console), that would be nice too :-)

2018-02-02 14:24 UTC, tnguyen1 commented on md/scenarios.md
> +|aws_iam_role|N| |Set this parameter if you want to assume a specific role while deploying. It's useful in an AWS organization with IAM users and multiple AWS accounts. See [AWS Organizations](aws_or
- This is the documentation of this parameter from `ec2.ini`. Maybe we could add this sentence or rephrase it:

> An IAM role can be assumed, so all requests are run as that role.                                                                                                                                                                          
> This can be useful for connecting across different accounts, or to limit user
> access

- We could rephrase the current sentence as: "Set this parameter if you want to assume an IAM role while deploying on AWS. It is useful in an AWS organization with IAM users and multiple AWS accounts. See [AWS Organizations](aws_organizations.md)"

- Maybe the parameter could be named `aws_assumed_iam_role` to be more explicit?

2018-02-02 14:24 UTC, tnguyen1 commented on md/scenarios.md
> +|aws_sso|N| |Set this parameter if you want to use [Gsuite SSO](aws_sso_using_gsuite.md)|gsuite|
As far as I understood (and according to https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html), we should rename this parameter into something like `aws_use_temporary_credentials=true/false`.

Then the documentation could be: 
|aws_use_temporary_credentials|N| |Set to `true` when using [AWS temporary security credentials](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html). Set to `false`when using long-term security credentials such as IAM user credentials.|true|

2018-02-02 14:24 UTC, tnguyen1 commented on md/scenarios.md
> +|ec2_iam_role|N| |The role name to apply through a profile instance to ec2 instances of a cluster in order to permit ec2 autodiscovery|ClusterBCD|
Maybe rephrasing: "Name of the IAM role to attach to EC2 instances to allow Hazelcast EC2 auto-discovery. This is MANDATORY when deploying a Bonita cluster on AWS with BCD."

Maybe the parameter could be renamed `ec2_discovery_iam_role` ?

2018-02-05 13:55 UTC, JeremJR commented
@tnguyen1 I've tried to apply your feedback https://github.com/bonitasoft/bonita-continuous-delivery-doc/pull/24/commits/c6ebb0e3f32d4f344b271fd1409fedb3c9cdeb22

2018-02-15 15:47 UTC, JeremJR commented
I close this PR an will reopen a new one. In the meantime I separate the modifications related to the cluster role for autodiscovery in another PR https://github.com/bonitasoft/bonita-continuous-delivery-doc/pull/29

2018-02-15 15:47 UTC, closed without merging