feat(doc): add how to configure REST API authorization (BCD-152)
bonitasoft/bonita-continuous-delivery-doc pull request #31
Opened 2018-02-16 16:40 UTC by JeremJR

2018-02-16 16:50 UTC, rbioteau requested changes

2018-02-16 16:50 UTC, rbioteau commented on md/how_to_configure_rest_api_authorization.md
> +So to dactivate dynamic permissions checks you will need to use the [custom initialization mechanism](https://documentation.bonitasoft.com/bcd/${varVersion}/custom_init) by adding this kind of script
`deactivate `

2018-02-16 16:59 UTC, JeremJR commented on md/how_to_configure_rest_api_authorization.md
> +So to dactivate dynamic permissions checks you will need to use the [custom initialization mechanism](https://documentation.bonitasoft.com/bcd/${varVersion}/custom_init) by adding this kind of script
thank you for the review during your day off! fix https://github.com/bonitasoft/bonita-continuous-delivery-doc/pull/31/commits/fb56cf3ce0dc48ae5a69893b36e5fc5a5d873b15

2018-02-22 14:15 UTC, rbioteau approved these changes

2018-02-27 16:29 UTC, rbioteau commented on md/how_to_configure_rest_api_authorization.md
> +For a more complex configuration you can also provide directly a file `roles/bonita/files/custom-init.d/custom-permissions-mapping.properties` and push it with a script like `roles/bonita/files/custo
For a more `advanced` configuration seems better here

2018-03-02 09:29 UTC, merged