add GSuite SSO support BCD-195
bonitasoft/bonita-continuous-delivery-doc pull request #37
Opened 2018-03-16 10:29 UTC by JeremJR

2018-03-20 11:24 UTC, tnguyen1 requested changes

2018-03-20 11:24 UTC, tnguyen1 commented on md/aws_prerequisites.md
> +In order to use Amazon EC2 instances, some configuration steps need to be performed as a prerequisite.
For Markdown to fulfill "new line break", 2 spaces must be added to the end of the line.
(Here spaces have been removed after "... as a prerequisite.") Consequently this paragraph renders on  single line.
http://doc.rd.lan:10037/bcd/2.0/aws_prerequisites

2018-03-20 11:24 UTC, tnguyen1 commented on md/aws_sso.md
> +# Single Sign-On
This new page is missing from taxonomy.
Maybe adding an entry in "Tutorials" like "AWS Single Sign-On"?

2018-03-20 11:24 UTC, tnguyen1 commented on md/aws_sso.md
> +# Single Sign-On
Title might be "# AWS Single Sign-On" instead if it applies to AWS only.

2018-03-20 11:24 UTC, tnguyen1 commented on md/aws_prerequisites.md
> +More details are available regarding:
rephrasing:
```Further configuration instructions for **AWS SIngle Sign-On** can be found [on this page](aws_sso.md).```

2018-03-20 11:24 UTC, tnguyen1 commented on md/aws_sso.md
> +If you implement this kind of authentication, when you start the BCD Controller container it won't be necessary to mount the boto file anymore.
formatting:
```... it will no longer be necessary to mount the `.boto` file.```

2018-03-20 11:24 UTC, tnguyen1 commented on md/aws_sso.md
> +In this step we will provide you an example using G Suite.
wording: "... using G Suite from Google."

2018-03-20 11:24 UTC, tnguyen1 commented on md/aws_sso.md
> +First, set up a Single Sign-On to AWS using G Suite as described into the [AWS website](https://aws.amazon.com/es/blogs/security/how-to-set-up-federated-single-sign-on-to-aws-using-google-apps/).
wording: ```... as described in [AWS website](https://aws.amazon.com/es/blogs/security/how-to-set-up-federated-single-sign-on-to-aws-using-google-apps/).```

2018-03-20 11:24 UTC, tnguyen1 commented on md/aws_sso.md
> +You will need to know Google's assigned Identity Provider ID (idp-id) and the ID that they assign to the SAML service provider (sp-id).
wording: ```... and the ID assigned to the SAML ...```

2018-03-20 11:24 UTC, tnguyen1 commented on md/aws_sso.md
> +The `idp-id` can be found into `Security > Set up single sign-on (SSO)` in the SSO url provided `https://accounts.google.com/o/saml2/idp?idpid=123456789012`
rephrasing:
````idp-id` can be found on Google Admin `Security > Set up single sign-on (SSO)` page in the SSO URL provided. For instance: `https://accounts.google.com/o/saml2/idp?idpid=123456789012````

2018-03-20 11:24 UTC, tnguyen1 commented on md/aws_sso.md
> +The `sp-id` can be found into `Apps > SAML Apps > Amazon Web Services` in the browser url you will see `#AppDetails:service=123456789012`
rephrasing:
````sp-id` can be found in the URL of your web browser when viewing Google Admin `Apps > SAML Apps > Amazon Web Services` page . For instance: `#AppDetails:service=123456789012````

2018-03-20 11:24 UTC, tnguyen1 commented on md/aws_sso.md
> +The `sp-id` can be found into `Apps > SAML Apps > Amazon Web Services` in the browser url you will see `#AppDetails:service=123456789012`
AFAIKwe haven't mentioned the AWS SAML application in the doc before. Should we explain how to activate it?

2018-03-20 11:24 UTC, tnguyen1 commented on md/release_notes.md
> +- Add G-Suite SSO support
wording: ```Add Google G Suite SSO support```

2018-03-20 13:59 UTC, JeremJR commented on md/aws_sso.md
> +The `sp-id` can be found into `Apps > SAML Apps > Amazon Web Services` in the browser url you will see `#AppDetails:service=123456789012`
In fact it's described into 
>First, set up a Single Sign-On to AWS using G Suite as described in [AWS website](https://aws.amazon.com/es/blogs/security/how-to-set-up-federated-single-sign-on-to-aws-using-google-apps/).

2018-03-20 14:01 UTC, JeremJR commented on md/release_notes.md
> +- Add G-Suite SSO support
fix https://github.com/bonitasoft/bonita-continuous-delivery-doc/pull/37/commits/87d0628f7bb18c98df6441992b222c79550d381f

2018-03-27 09:13 UTC, tnguyen1 approved these changes

2018-03-27 09:15 UTC, merged