Document how to handle BCD failuers (BCD-147) and how to access Bonit…
bonitasoft/bonita-continuous-delivery-doc pull request #38
Opened 2018-03-20 12:22 UTC by JeremJR

…a logs (BCD-146)

2018-03-22 15:02 UTC, alarreine reviewed
Is it better to have a file for each "trouble"? 
* Troubleshooting
  * Issue 1
  * Issue 2

2018-03-23 14:10 UTC, JeremJR commented
@alarreine I've changed the structure, what do you think about it?

2018-03-23 16:48 UTC, alarreine approved these changes

2018-03-26 12:53 UTC, tnguyen1 requested changes
My main feedback would be to avoid multiplicating very short pages, I'm feling that makes searching in different pages less convenient that searching in fewer pages.
Some new pages here only have 2 lines of content.

2018-03-26 12:53 UTC, tnguyen1 commented on md/accessing_bonita_logs.md
> +You can know display the logs using:
I guess you mean `Now you can display the logs using:`

2018-03-26 12:53 UTC, tnguyen1 commented on md/accessing_bonita_logs.md
> +It's possible through the bcd status command:
Might be good to highlight commands like:

... It's possible through the `bcd status` command: ...

2018-03-26 12:53 UTC, tnguyen1 commented on md/accessing_bonita_logs.md
> +If you want to copy all the logs (bonita, catalina) you can use docker cp:
Might be good to highlight commands like:
... you can use `docker cp`: ...

2018-03-26 12:53 UTC, tnguyen1 commented on md/accessing_bonita_logs.md
> +Then you will be able to retrieve all the files through a scp:
... all the files using `scp`: ...

2018-03-26 12:53 UTC, tnguyen1 commented on md/debugging_facts.md
> +# Debugging Facts
Is it worth having a separate page for this content? Or should we include it to a more general "troubleshooting" page?

2018-03-26 12:53 UTC, tnguyen1 commented on md/invalid_amiid_subnetid.md
> +# InvalidAMIID.NotFound and InvalidSubnetID.NotFound
Same comment: Is it worth having a separate page for this content?

2018-03-26 12:53 UTC, tnguyen1 commented on md/state_management.md
> +# State management
Same comment: Is it worth having a separate page for this content?

2018-03-26 13:34 UTC, alarreine commented
It's true that almost everyone write all the troubleshootings in one page like :
* https://helpx.adobe.com/download-install/kb/troubleshoot-creative-cloud-activation-errors.html
* https://ionicframework.com/docs/troubleshooting/
* https://facebook.github.io/react-native/docs/troubleshooting.html

2018-03-26 13:38 UTC, alarreine commented on md/invalid_amiid_subnetid.md
> +You should check that `ec2_subnet_ids` and `aws_ami` correspond to the region set into `ec2_region`.
Other thing to check:
- It there is a .aws folder. I have the same error when I forgot to the signing step with `aws-google-auth`

2018-03-27 08:51 UTC, JeremJR commented on md/invalid_amiid_subnetid.md
> +You should check that `ec2_subnet_ids` and `aws_ami` correspond to the region set into `ec2_region`.
As seen together you had an empty .aws folder and a .boto file so the .boto file was used. Adding a comment about that in https://github.com/bonitasoft/bonita-continuous-delivery-doc/pull/38/commits/672865fb0de82b66f00afe541f5e4e37cab253c9

2018-03-29 13:11 UTC, tnguyen1 commented on md/troubleshooting_guide.md
> +This command will identify every EC2 instance (regardless of `bcd_stack_id`) and put its facts into the `tmp_facts` directory.
- I think this sentence is no longer true. It seems to be using ec2.ini which filters on bcd_stack_id.
- Besides, we should specify to change to the `ansible` directory prior to launching this command or it will not work.

2018-03-29 13:12 UTC, tnguyen1 commented on md/troubleshooting_guide.md
> +If you enconter issues during the usage of BCD due to a bad configuration or a network problem, it's interesting to know that you could be able to simply relaunch your command (create, deploy) after
Typo: encounter

2018-03-29 13:12 UTC, tnguyen1 commented on md/troubleshooting_guide.md
> +iIf while you launch a `create` command in order to create instances on AWS you get errors like these:
Typo: If

2018-03-30 08:59 UTC, JeremJR commented on md/troubleshooting_guide.md
> +This command will identify every EC2 instance (regardless of `bcd_stack_id`) and put its facts into the `tmp_facts` directory.
fix https://github.com/bonitasoft/bonita-continuous-delivery-doc/pull/38/commits/26e87058a01efde1af1f578427cb113a9e8bd50e

2018-03-30 08:59 UTC, JeremJR commented on md/troubleshooting_guide.md
> +If you enconter issues during the usage of BCD due to a bad configuration or a network problem, it's interesting to know that you could be able to simply relaunch your command (create, deploy) after
fix https://github.com/bonitasoft/bonita-continuous-delivery-doc/pull/38/commits/96395174d496f26e0aa7c8afaaf3374157683615

2018-03-30 08:59 UTC, JeremJR commented on md/troubleshooting_guide.md
> +iIf while you launch a `create` command in order to create instances on AWS you get errors like these:
fix https://github.com/bonitasoft/bonita-continuous-delivery-doc/pull/38/commits/96395174d496f26e0aa7c8afaaf3374157683615

2018-03-30 14:21 UTC, tnguyen1 approved these changes

2018-03-30 14:23 UTC, tnguyen1 commented
OK for the changes, thanks.
Then we should update this page for 2.0 documentation with another PR I guess.

2018-03-30 14:23 UTC, merged