tr(structure): rework doc structure for release 2.0
bonitasoft/bonita-continuous-delivery-doc pull request #41
Opened 2018-03-28 16:33 UTC by tnguyen1

A global rework of BCD documentation in preparation to 2.0 release.

2018-03-30 09:02 UTC, alarreine commented on md/aws_prerequisites.md
> +Bonita Provisioning solution uses official Ubuntu cloud images as EC2 AMI (Amazon Machine Images).
BCD use == only use OR only support?

2018-03-30 09:41 UTC, alarreine commented on md/bcd_cli.md
> +The BCD CLI allows to invoke more than one command in one go. This is useful to chain commands as a pipeline.
Is it better?
The BCD CLI allows invoking more..
or
The BCD CLI allows you to invoke more..

The verb invoke is usually in the gerund form when following the word allows.

2018-03-30 09:41 UTC, alarreine commented on md/bcd_cli.md
> +* First the `bcd` command requires that the **`BCD_HOME`** environment variable is set.
Is it better?
First, the `bcd` command

2018-03-30 09:41 UTC, alarreine commented on md/bcd_cli.md
> +* Next the `bcd` command takes a mandatory option called `scenario` through the `-s / --scenario` command line option.
Is it better?
Next, the `bcd` command

2018-03-30 09:41 UTC, alarreine commented on md/bcd_cli.md
> +* Finally the BCD CLI expects to find Bonita version-specific dependencies in the **`$BCD_HOME/dependencies`** directory. This directory must contain:
Is it better?
 Finally, the BCD CLI expects

2018-03-30 09:48 UTC, JeremJR commented on md/livingapp_build.md
> +-rw-rw-r-- 1 1000 1000 8,7M Mar 29 16:16 bonita-sp-7.6.3-maven-repository.zip
even if for test we use this at the moment, shouldn't we put the same version in the documentation?

2018-03-30 13:37 UTC, JeremJR commented on md/aws_sso.md
> +# AWS single sign-on
maybe that we can also use for this page the `<!--{.h1}-->`, `<!--{.h2}-->` as it's a bit strange to have a toc with only 'Single Sign-On to AWS Using G Suite' ?

2018-03-30 13:40 UTC, JeremJR requested changes

2018-03-30 13:40 UTC, JeremJR commented on md/scenarios.md
> +|lic_type|Type of license in [production|development|qualification|trial].|trial|
missing `'\'` should be : [production\|development\|qualification\|trial]

2018-03-30 16:02 UTC, tnguyen1 commented on md/bcd_cli.md
> +The BCD CLI allows to invoke more than one command in one go. This is useful to chain commands as a pipeline.
Basically I have used what's in the Click documentation: http://click.pocoo.org/5/commands/#multi-command-chaining

2018-03-30 16:04 UTC, tnguyen1 commented on md/bcd_cli.md
> +* First the `bcd` command requires that the **`BCD_HOME`** environment variable is set.
yep looks better :-) https://www.italki.com/question/84025

2018-03-30 16:18 UTC, tnguyen1 commented
I have integrated your feedback with commit dba3fc7

2018-04-03 07:14 UTC, JeremJR approved these changes

2018-04-03 07:14 UTC, merged