Feat(doc) include doc deployer in doc bcd
bonitasoft/bonita-continuous-delivery-doc pull request #48
Opened 2018-04-13 09:29 UTC by alachambre

closes [BS-18284](https://bonitasoft.atlassian.net/browse/BS-18284)

2018-04-13 09:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bonitasoft/bonita-continuous-delivery-doc?pullRequest=48) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/bonitasoft/bonita-continuous-delivery-doc?pullRequest=48) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: alachambre<br/>:x: tbouffard<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bonitasoft/bonita-continuous-delivery-doc?pullRequest=48) it.</sub>

2018-04-13 14:32 UTC, tbouffard requested changes
Mainly some formal and typo to fix

2018-04-13 14:32 UTC, tbouffard commented on md/livingapp_deploy.md
> +
⚠️ we should add a link to the how to configure rest api authorization here to let the user understand that the deployer does not managed them

2018-04-13 14:32 UTC, tbouffard commented on md/livingapp_buid_and_deploy.md
> +As example, if you want to use Bonita to build a _loan application_ and a _leave request application_, we strongly advise you to manage those two projects in two different repositories. It will allow
👍 for the example

2018-04-13 14:32 UTC, tbouffard commented on md/livingapp_buid_and_deploy.md
> +Since the version 7.7.0, the popular Version Control System _Git_ is integrated in Bonita. It is a fine way to manage properly the versioning of your projects.
❓ we may add a link to the Bonita Collaboration documentation here

2018-04-13 14:32 UTC, tbouffard commented on md/livingapp_buid_and_deploy.md
> +The recommended way is definitively to  keep the latest version of each resources in the working repository, and the history on your Version Control System.
extra space between 'to' and 'keep'

2018-04-13 14:32 UTC, tbouffard commented on md/livingapp_buid_and_deploy.md
> +This is the simplest use case: you want to build a Bonita repository and deploy all associated resources.
⚠️ for consistency, we should rename `Bonita repository` into `Bonita Living Application repository`

2018-04-13 14:32 UTC, tbouffard commented on md/livingapp_buid_and_deploy.md
> +This command will first build the Bonita repository. The output of the build is a zip file, located in a folder _target_ created by the builder. This zip file corresponds to the _Application Archive_
⚠️ consistency, see above
⚠️ `It contains all the resources of the input repository, built` --> `It contains all resources built from the input repository`

2018-04-13 14:32 UTC, tbouffard commented on md/livingapp_buid_and_deploy.md
> +Sometimes, you may need to perform some actions between the build and the deploy . You may want to deploy only a sub part of the repository that has been built, or add some external resources in the
⚠️ 1st sentence the dot should be close to 'deploy'

2018-04-13 14:32 UTC, tbouffard commented on md/livingapp_buid_and_deploy.md
> + - **Build** a Bonita repository with BDC
⚠️ typo BDC --> BCD

2018-04-13 14:32 UTC, tbouffard commented on md/livingapp_buid_and_deploy.md
> +#### Example 1: I only want to deploy the Business Data Model from my Bonita repository
👍  for the 3 examples, very clear

2018-04-16 07:59 UTC, alachambre commented on md/livingapp_buid_and_deploy.md
> +This is the simplest use case: you want to build a Bonita repository and deploy all associated resources.
disagree, it would be if it was possible to have an other kind of Bonita repository, but it's nor, so it would just add some confusion here in my view.

2018-04-17 09:42 UTC, JeremJR commented
replaced by https://github.com/bonitasoft/bonita-continuous-delivery-doc/pull/49

2018-04-17 09:42 UTC, closed without merging