Documentation deploy Bonita vagrant BCD-218
bonitasoft/bonita-continuous-delivery-doc pull request #57
Opened 2018-04-30 15:07 UTC by alarreine

2018-05-02 09:06 UTC, JeremJR requested changes

2018-05-02 09:06 UTC, JeremJR commented on md/on_premise_vagrant.md
> +BCD can not only deploy you Bonita Stack in the cloud. You can also deploy your stack on-premises hosts.
typo : your Bonita Stack

2018-05-02 09:06 UTC, JeremJR commented on md/on_premise_vagrant.md
> +This example uses an insecure private key...
It's a bit scary but maybe we can point to the official doc in order to explain why? https://www.vagrantup.com/docs/vagrantfile/ssh_settings.html

2018-05-02 09:06 UTC, JeremJR commented on md/on_premise_vagrant.md
> +You can access to your to your bonita application in http://192.168.10.10:8081/bonita
maybe we can also add a section explaing how to stop/clean up the vagrant box?

2018-05-02 09:18 UTC, tbouffard requested changes

2018-05-02 09:18 UTC, tbouffard commented on md/on_premise_vagrant.md
> +An example of `Vagrantfile` is provided in your `bonita-continuous-delivery_<version>/vagrant/1-machine` directory.
❓ You may add that examples are given for VirtualBox and so VirtualBox must be installed on the host machine.
This is described later in the documentation but this may be documented here in the requirements section for clarity

2018-05-02 09:18 UTC, tbouffard commented on md/on_premise_vagrant.md
> +On this page you will find usage examples and references about how to deploy your stack with Vagrant.
⚠️ Notice that what is described here doesn't work for people running BCD on windows 10 Pro and who would like to run VMs on the same host.
In this case, Windows Hyperv must be activated to have Docker running and VirtualBox cannot work along with the Hyperv.

So I suggest to add a disclaimer in this page to warn end-user running on Windows that they can not use our examples Vagrant boxes out of the box.

2018-05-02 09:18 UTC, tbouffard commented on md/on_premise_vagrant.md
> +An example of `Vagrantfile` is provided in your `bonita-continuous-delivery_<version>/vagrant/1-machine` directory.
⚠️ you may add that the VM must be able to access to the Internet as some packages will be updated/installed on the VM

2018-05-02 12:46 UTC, alarreine commented on md/on_premise_vagrant.md
> +You can access to your to your bonita application in http://192.168.10.10:8081/bonita
Change in commit [9ed3924](https://github.com/bonitasoft/bonita-continuous-delivery-doc/pull/57/commits/9ed392475314273a4603d4c7824ef957d50a33af)

2018-05-02 12:47 UTC, alarreine commented on md/on_premise_vagrant.md
> +This example uses an insecure private key...
Change in commit 9ed3924

2018-05-02 12:47 UTC, alarreine commented on md/on_premise_vagrant.md
> +BCD can not only deploy you Bonita Stack in the cloud. You can also deploy your stack on-premises hosts.
Change in commit 9ed3924

2018-05-02 12:47 UTC, alarreine commented on md/on_premise_vagrant.md
> +On this page you will find usage examples and references about how to deploy your stack with Vagrant.
Change in commit 9ed3924

2018-05-02 15:11 UTC, tnguyen1 commented
retest this please

2018-05-02 16:16 UTC, tnguyen1 requested changes
- As discussed, I would have expected a tutorial about on-premises deployment where Vagrant is an example we provide.
We would then explain static inventory for instance.
- Please check the rendered page for obvious typos. Thanks.

2018-05-02 16:16 UTC, tnguyen1 commented on md/on_premise_vagrant.md
> +::: Attention
The supported syntax for this is described here: https://www.npmjs.com/package/markdown-it-alerts
Please check the rendered page before submitting a PR.

2018-05-02 16:16 UTC, tnguyen1 commented on md/on_premise_vagrant.md
> +On this page you will find usage examples and references about how to deploy your stack with Vagrant.
Putting the link to Vagrant on the first occurence may help.
Also a short note about Vagrant could be added I think.

2018-05-02 16:16 UTC, tnguyen1 commented on md/on_premise_vagrant.md
> +An example of `Vagrantfile` is provided in your `bonita-continuous-delivery_<version>/vagrant/1-machine` directory.
Actually there are 2 Vagrant examples in the `bonita-continuous-delivery_<version>/vagrant` directory.

2018-05-02 16:16 UTC, tnguyen1 commented on md/on_premise_vagrant.md
> +named **vagrant_single.yml.EXAMPLE** is provided in the **bonita-continuous-delivery_<version>/scenarios**. For more
\<version\> is not rendered well here. Maybe because of the formatting.

2018-05-02 16:16 UTC, tnguyen1 commented on md/on_premise_vagrant.md
> +* Finally, the virtual machine that you will create has must be able to access to the Internet because some packages will be updated/installed.
whether "must be able to access the Internet"
or "must have access to the Internet"

I guess.

2018-05-02 16:16 UTC, tnguyen1 commented on md/on_premise_vagrant.md
> +Here is a complete example using the configuration files provided
add a final dot to this line.

2018-05-02 16:16 UTC, tnguyen1 commented on md/on_premise_vagrant.md
> +$ docker run --rm -t -i --name bcd-controller -v $HOME/bonita-continuous-delivery_2.0.0/:/home/bonita/bonita-continuous-delivery
Might be easier to read if split on several lines. (see quickstart page)

2018-05-02 16:16 UTC, tnguyen1 commented on md/on_premise_vagrant.md
> +You can access to your to your bonita application in http://192.168.10.10:8081/bonita
"to your" is repeated.

I guess: "You should now be able to access Bonita Portal at http://192.168.10.10:8081/bonita."

2018-05-02 16:16 UTC, tnguyen1 commented on md/taxonomy.md
> +        * [Deploy with Vagrant](on_premise_vagrant.md)
As discussed, I would have expected a tutorial about on-premises deployment where Vagrant is an example we provide.
We would then explain static inventory for instance.

2018-05-29 15:48 UTC, JeremJR requested changes

2018-05-29 15:48 UTC, JeremJR commented on md/deploy_on_premise.md
> +# How to deploy Bonita on-premise
Due to that change https://github.com/bonitasoft/bonita-provisioning/commit/99e3bdedc519951cb720afa6b78a859300d5081c could you please reword on premise by static inventory?

2018-05-29 15:48 UTC, JeremJR commented on md/deploy_on_premise.md
> +* bcd_inventory: Ansible inventory path required when `bcd_provider` is `on-premises`
`static_inventory`

2018-05-29 15:48 UTC, JeremJR commented on md/deploy_on_premise.md
> +* bcd_provider: Infrastructure provider. It has to be set with `on-premises`
`static_inventory`

2018-05-29 15:48 UTC, JeremJR commented on md/taxonomy.md
> +        * [Deploy on-premise](deploy_on_premise.md)
Deploy on existing servers?

2018-05-29 15:48 UTC, JeremJR commented on md/deploy_on_premise.md
> +You can see an example of scenario in `bonita-continuous-delivery_x.x.x/scenarios/on_premise.yml.EXAMPLE`
`static_inventory.yml.EXAMPLE`?

2018-05-29 15:48 UTC, JeremJR commented on md/deploy_on_premise.md
> +and `on-premise-1-machine.EXAMPLE` in the same directory.
`static-inventory-1-machine.EXAMPLE`?

2018-05-29 15:53 UTC, JeremJR commented
could you please also rebase your branch on 2.0 branch? :)

2018-05-31 09:59 UTC, JeremJR approved these changes

2018-05-31 10:17 UTC, merged