Release 2.0.1
bonitasoft/bonita-continuous-delivery-doc pull request #84
Opened 2018-07-31 10:10 UTC by alarreine

2018-07-31 11:51 UTC, JeremJR requested changes

2018-07-31 11:51 UTC, JeremJR commented on md/release_notes.md
> +* BCD-242 Fix version of all dependencies.
BCD-274 Fix dependencies version of the license module?

2018-07-31 11:51 UTC, JeremJR commented on md/release_notes.md
> +* BCD-274 Fix Docker Engine security configuration.
BCD-274 Security fix : disable Docker daemon tcp socket listening?

2018-07-31 11:51 UTC, JeremJR commented on md/release_notes.md
> -## Breaking changes
The Breaking changes introduced by BCD 2.0 remain true.

2018-07-31 15:35 UTC, alarreine commented on md/release_notes.md
> -## Breaking changes
[PR](https://github.com/bonitasoft/bonita-continuous-delivery-doc/pull/84/commits/8b3bd90f435ab80f6e4e1e2b0ca0860b17ceff86)

2018-07-31 15:35 UTC, alarreine commented on md/release_notes.md
> +* BCD-274 Fix Docker Engine security configuration.
[PR](https://github.com/bonitasoft/bonita-continuous-delivery-doc/pull/84/commits/8b3bd90f435ab80f6e4e1e2b0ca0860b17ceff86)

2018-07-31 15:35 UTC, alarreine commented on md/release_notes.md
> +* BCD-242 Fix version of all dependencies.
[PR](https://github.com/bonitasoft/bonita-continuous-delivery-doc/pull/84/commits/8b3bd90f435ab80f6e4e1e2b0ca0860b17ceff86)

2018-08-01 12:50 UTC, JeremJR approved these changes

2018-08-02 13:55 UTC, JeremJR approved these changes

2018-08-02 13:55 UTC, merged